import type { Metadata } from "next";
import { fontSans, fontSerif } from "@/lib/fonts";
import "@/styles/globals.css";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "AI Ignition",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${fontSans.variable} ${fontSerif.variable}`}
    >
      <body>
        <Header />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
