import type { Metadata } from "next";
import { fontSans } from "@/lib/fonts";
import "@/styles/globals.css";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "AI Ignition",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontSans.variable}>
        <Header />
        <main className="container mx-auto">{children}</main>
      </body>
    </html>
  );
}
